### PR TITLE
port dispatch.clj

### PR DESCRIPTION
**Pull request by swannodette**
no tests yet. fix cljs.pprint macro file, need to use cljs.core/binding not clojure.core/binding

### CODE REVIEW

**Comment by bostonou** [comment]
I already have some of this completed in another branch, with tests, so I'll work on merging.

**Comment by bostonou** [comment]
This PR and my [working branch](https://github.com/shaunlebron/cljs-pprint/tree/finish-out-port) fail tests in different ways. I won't be able to look at this more until later tonight.

Would it be easier for you to get write perms for the repo @swannodette ?

**Comment by swannodette** [comment]
@bostonou I'm OK sending PRs as I'm less familiar with everything that's been done and my stuff will likely need review like this one. I ran the tests with these changes with:

```
lein cljsbuild once test
```

And I didn't see any failures. How are you running the tests?

Or are you saying that the tests fail in your branch once you merge this PR?

**Comment by bostonou** [comment]
[These new tests](https://github.com/shaunlebron/cljs-pprint/blob/master/src/cljs/cljs/pprint.cljs#L1941-L1946) (in my branch) are the failing tests I'm referring to.

There are some general issues in printing cljs code vs clj code that need to be discussed, plus some of my lack of understanding on some of the details. So the tests may not be exactly correct, but our branches fail in different ways.

Regarding cljs/clj differences, the differences in the readers seem to cause issues. Specifically:
- the cljs reader choked on anonymous functions
- the cljs/clj EDN readers differ on how they read `@`, though I think your branch may address this

**Comment by bostonou** [comment]
I'm ok with merging this PR, then applying my additions to that. Seems like the easiest way forward.

**Pull request merged**
